# run as: 
# export USER="$(id -u):$(id -g)"
# sudo --preserve-env=USER docker compose up --build
services:
  app:
    build: .
    image: msi-pipeline-dashboard
    container_name: msi-pipeline-dashboard
    user: ${USER}
    ports:
      - "8050:8050"
    volumes:
      - ./:/app
      - ./data:/data
      - ./jobs:/jobs
      - ./logs:/logs
      - ./tools:/tools
    command: python app.py