from dash import Input, Output, State, callback, no_update
from dash_iconify import DashIconify

from components.helper import helper
from components.notifications import job_started_notification, job_started_failed_notification
from services.job_manager import create_job
from services.file_manager import get_files, build_output_name

from configs.tools import TOOLS
from configs.paths import data_path, MICROSAT_LIST_EXT, BED_EXT

import dash
import dash_mantine_components as dmc

dash.register_page(__name__, path="/microsat2bed")

tool = TOOLS["microsat2bed"]

def make_convert():
    main_options = dmc.Paper(
        withBorder=True,
        radius="md",
        p="md",
        h="100%",
        children=dmc.Stack(
            [
                dmc.Title("Main options", order=4),
                dmc.Select(
                    label=dmc.Group(
                        [
                            dmc.Text("Microsatellite list file", size="sm", fw=500),
                            dmc.Text("*", c="red", size="sm", fw=700),
                            helper("Select a microsatellite list file generated by MSIsensor scan."),
                        ],
                        gap=6,
                    ),
                    id="microsat2bed-convert-microsat-list-file-select",
                    data=[
                        {"value": str(file), "label": str(file).replace(data_path, "")}
                        for file in get_files(extensions=MICROSAT_LIST_EXT)
                    ],
                    nothingFoundMessage="Nothing found",
                    checkIconPosition="right",
                    placeholder="Select MSIsensor microsatellite list file",
                    searchable=True,
                ),
                
                dmc.Box(style={"flexGrow": 1}),

                dmc.TextInput(
                    label=dmc.Group(
                        [
                            dmc.Text("Output file name", size="sm", fw=500),
                            helper("Optional. Enter a custom output file name without extension. The .bed extension will be added automatically."),
                        ],
                        gap=6,
                    ),
                    id="microsat2bed-convert-output-name-input",
                    placeholder="Leave empty to use the default file name",
                ),

                dmc.Button("Start", id="microsat2bed-convert-start-button", disabled=True),
            ],
            gap="md",
            h="100%",
        ),
    )

    return dmc.Grid(
        [
            dmc.GridCol(main_options, span=12),
        ],
        gutter="md",
        align="stretch",
    )

command_description = dmc.Paper(
    withBorder=True,
    radius="md",
    p="md",
    w="100%",
    children=dmc.Stack(
        [
            dmc.Text(
                tool.commands["convert"].description,
                style={"whiteSpace": "pre-line"},
            ),
        ],
        gap="xs",
    ),
)

layout = dmc.Container(
    dmc.Stack(
        [
            dmc.Title(tool.name, order=2),
            dmc.Text(tool.description),
            dmc.Group(
                [
                    DashIconify(icon="bi:github", width=18),
                    dmc.Anchor(
                        "Tool source code on GitHub",
                        href="https://github.com/dencoderexe/",
                        target="_blank",
                    ),
                ],
                gap="xs",
            ),
            command_description,
            make_convert(),
        ],
        gap="md",
    ),
    fluid=True,
    p="md",
)
    
@callback(
    Output("microsat2bed-convert-start-button", "disabled"),
    Input("microsat2bed-convert-microsat-list-file-select", "value"),
)
def microsat2bed_convert_start_button(microsatellite_list):
    return not bool(microsatellite_list)

@callback(
    Output("notification-container", "sendNotifications", allow_duplicate=True),
    Input("microsat2bed-convert-start-button", "n_clicks"),
    State("microsat2bed-convert-microsat-list-file-select", "value"),
    State("microsat2bed-convert-output-name-input", "value"),
    prevent_initial_call=True,
)
def microsat2bed_convert_start_job(
    n_clicks,
    microsatellite_list,
    output_name,
):
    if not n_clicks:
        return no_update

    try:
        create_job(
            tool=tool,
            command=tool.commands.get("convert"),
            microsatellite_list=microsatellite_list,
            output=build_output_name(microsatellite_list, output_name, BED_EXT[0]),
        )

        return job_started_notification(f"{tool.name} started")

    except Exception as e:
        return job_started_failed_notification(e)
