from dash import Input, Output, State, callback, no_update, html
from dash_iconify import DashIconify

from components.helper import helper
from components.notifications import job_started_notification, job_started_failed_notification
from services.job_manager import create_job
from services.file_manager import get_files, build_output_name

from configs.tools import TOOLS
from configs.paths import data_path, MICROSAT_LIST_EXT, MICROSAT_LIST_PRO_EXT, BED_EXT

import os
import dash
import dash_mantine_components as dmc

dash.register_page(__name__, path="/mslist_converter")

tool = TOOLS["mslist-converter"]

def make_pro():
    main_options = dmc.Paper(
        withBorder=True,
        radius="md",
        p="md",
        h="100%",
        children=dmc.Stack(
            [
                dmc.Title("Main options", order=4),
                dmc.Select(
                    label=dmc.Group(
                        [
                            dmc.Text("Microsatellite list file", size="sm", fw=500),
                            dmc.Text("*", c="red", size="sm", fw=700),
                            helper("Select a microsatellite list file generated by MSIsensor scan."),
                        ],
                        gap=6,
                    ),
                    id="mslist-converter-pro-microsat-list-file-select",
                    data=[
                        {"value": str(file), "label": str(file).replace(data_path, "")}
                        for file in get_files(extensions=MICROSAT_LIST_EXT)
                    ],
                    nothingFoundMessage="Nothing found",
                    checkIconPosition="right",
                    placeholder="Select MSIsensor microsatellite list file",
                    searchable=True,
                ),
                
                dmc.Box(style={"flexGrow": 1}),

                dmc.TextInput(
                    label=dmc.Group(
                        [
                            dmc.Text("Output file name", size="sm", fw=500),
                            helper("Optional. Enter a custom output file name without extension. The .microsatellite.list.pro extension will be added automatically."),
                        ],
                        gap=6,
                    ),
                    id="mslist-converter-pro-output-name-input",
                    placeholder="Leave empty to use the default file name",
                ),

                dmc.Button("Start", id="mslist-converter-pro-start-button", disabled=True),
            ],
            gap="md",
            h="100%",
        ),
    )

    return dmc.Grid(
        [
            dmc.GridCol(main_options, span=12),
        ],
        gutter="md",
        align="stretch",
    )

def make_mantis():
    main_options = dmc.Paper(
        withBorder=True,
        radius="md",
        p="md",
        h="100%",
        children=dmc.Stack(
            [
                dmc.Title("Main options", order=4),
                dmc.Select(
                    label=dmc.Group(
                        [
                            dmc.Text("Microsatellite list file", size="sm", fw=500),
                            dmc.Text("*", c="red", size="sm", fw=700),
                            helper("Select a microsatellite list file generated by MSIsensor scan."),
                        ],
                        gap=6,
                    ),
                    id="mslist-converter-mantis-microsat-list-file-select",
                    data=[
                        {"value": str(file), "label": str(file).replace(data_path, "")}
                        for file in get_files(extensions=MICROSAT_LIST_EXT)
                    ],
                    nothingFoundMessage="Nothing found",
                    checkIconPosition="right",
                    placeholder="Select MSIsensor microsatellite list file",
                    searchable=True,
                ),
                
                dmc.Box(style={"flexGrow": 1}),

                dmc.TextInput(
                    label=dmc.Group(
                        [
                            dmc.Text("Output file name", size="sm", fw=500),
                            helper("Optional. Enter a custom output file name without extension. The .bed extension will be added automatically."),
                        ],
                        gap=6,
                    ),
                    id="mslist-converter-mantis-output-name-input",
                    placeholder="Leave empty to use the default file name",
                ),

                dmc.Button("Start", id="mslist-converter-mantis-start-button", disabled=True),
            ],
            gap="md",
            h="100%",
        ),
    )

    return dmc.Grid(
        [
            dmc.GridCol(main_options, span=12),
        ],
        gutter="md",
        align="stretch",
    )

command_select = dmc.Paper(
    withBorder=True,
    radius="md",
    p="md",
    w="100%",
    children=dmc.Stack(
        [
            dmc.Title("Command", order=4),
            dmc.Select(
                label="Choose a command",
                id="mslist-converter-command-select",
                value="msisensor-pro",
                data=[
                    {"value": command.key, "label": command.name}
                    for command in tool.commands.values()
                ],
                allowDeselect=False,
            ),
            dmc.Text(
                id="mslist-converter-command-description",
                style={"whiteSpace": "pre-line"},
            ),
        ],
        gap="xs",
    ),
)

def layout():
    return dmc.Container(
        dmc.Stack(
            [
                dmc.Title(tool.name, order=2),
                dmc.Text(tool.description),
                dmc.Group(
                    [
                        DashIconify(icon="bi:github", width=18),
                        dmc.Anchor(
                            "Tool source code on GitHub",
                            href="https://github.com/dencoderexe/FIIT-16768-127130-PUBLIC/blob/main/tools/mslist-converter.py",
                            target="_blank",
                        ),
                    ],
                    gap="xs",
                ),
                command_select,
                html.Div(id="mslist-converter-command-container"),
            ],
            gap="md",
        ),
        fluid=True,
        p="md",
    )

@callback(
    Output("mslist-converter-command-container", "children"), 
    Input("mslist-converter-command-select", "value"),
)
def mslist_converter_select_command(value):
    if value == "msisensor-pro":
        return make_pro()
    elif value == "mantis":
        return make_mantis()
    else:
        return None

@callback(
    Output("mslist-converter-pro-start-button", "disabled"),
    Input("mslist-converter-pro-microsat-list-file-select", "value"),
)
def mslist_converter_pro_start_button(microsatellite_list):
    return not bool(microsatellite_list)

@callback(
    Output("notification-container", "sendNotifications", allow_duplicate=True),
    Input("mslist-converter-pro-start-button", "n_clicks"),
    State("mslist-converter-command-select", "value"),
    State("mslist-converter-pro-microsat-list-file-select", "value"),
    State("mslist-converter-pro-output-name-input", "value"),
    prevent_initial_call=True,
)
def mslist_converter_pro_start_job(
    n_clicks,
    command_key,
    microsatellite_list,
    output_name,
):
    if not n_clicks:
        return no_update

    try:
        create_job(
            tool=tool,
            command=tool.commands.get(command_key),
            microsatellite_list=microsatellite_list,
            output=build_output_name(microsatellite_list, output_name, MICROSAT_LIST_PRO_EXT[0]),
        )

        return job_started_notification(f"{tool.name} pro started")

    except Exception as e:
        return job_started_failed_notification(e)

    
@callback(
    Output("mslist-converter-mantis-start-button", "disabled"),
    Input("mslist-converter-mantis-microsat-list-file-select", "value"),
)
def mslist_converter_mantis_start_button(microsatellite_list):
    return not bool(microsatellite_list)

@callback(
    Output("notification-container", "sendNotifications", allow_duplicate=True),
    Input("mslist-converter-mantis-start-button", "n_clicks"),
    State("mslist-converter-command-select", "value"),
    State("mslist-converter-mantis-microsat-list-file-select", "value"),
    State("mslist-converter-mantis-output-name-input", "value"),
    prevent_initial_call=True,
)
def mslist_converter_mantis_start_job(
    n_clicks,
    command_key,
    microsatellite_list,
    output_name,
):
    if not n_clicks:
        return no_update

    try:
        create_job(
            tool=tool,
            command=tool.commands.get(command_key),
            microsatellite_list=microsatellite_list,
            output=build_output_name(microsatellite_list, output_name, BED_EXT[0]),
        )

        return job_started_notification(f"{tool.name} mantis started")

    except Exception as e:
        return job_started_failed_notification(e)

@callback(
    Output("mslist-converter-command-description", "children"),
    Input("mslist-converter-command-select", "value"),
)
def mslist_converter_command_description(command_key):
    command = tool.commands.get(command_key)
    return command.description if command else "No description available."
